### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wodog** [NightCatSama/NightCAT-ChatRoom#1]
错误信息如下

``` sh
zhouchongyangdeMac-mini:NightCAT-ChatRoom zhouchongyang$ npm run start

> me@0.0.0 start /Users/zhouchongyang/Desktop/github/NightCAT-ChatRoom
> node ./bin/www

/Users/zhouchongyang/Desktop/github/NightCAT-ChatRoom/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/zhouchongyang/Desktop/github/NightCAT-ChatRoom/node_modules/mongoskin/lib/utils.js:33:43)
    at Object.<anonymous> (/Users/zhouchongyang/Desktop/github/NightCAT-ChatRoom/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
```

**Comment by NightCatSama** [comment]
@wodog 

/Users/zhouchongyang/Desktop/github/NightCAT-ChatRoom/node_modules/**mongoskin**/lib/utils.js:33

你看看你模块有没有错，我这里没有mongoskin模块，用的是monk模块，可能npm自动下载的模块更新过了，你可以试试单独下载monk模块看看

**Comment by wodog** [comment]
我再次安装模块的时候，报出这个信息

``` sh
zhouchongyangdeMac-mini:NightCAT-ChatRoom zhouchongyang$ npm install
npm WARN EPEERINVALID mongodb-core@1.2.32 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPEERINVALID mongoskin@1.4.13 requires a peer of mongodb@~1.4 but none was installed.
```

**Comment by NightCatSama** [comment]
@wodog 你在看package上看看需要哪些模块，然后你再把少的另外安装试试。npm stall monk之类的

**Comment by wodog** [comment]
我把mongodb的包换成了 **~1.4** , 就能正常运行了
之前自动下载的是 `mongodb@2.1.4`
果然是包依赖问题

``` sh
"dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.3.3",
    "express": "~4.13.1",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0",
    "mongodb": "~1.4",
    "monk": "*",
    "socket.io": "*"
  }
```

**Comment by NightCatSama** [comment]
@wodog 嗯~
